%YAML 1.2
---
# Config for the application
# --------------------------
als: &app
  test: test
  root_dir: /home/stas/dev/eclipse_workspace/AutomaticLendingSystem # change this
  keys_file: ~/.exchange_keys/keys.yml

  check_interval: 10

  lending_rate_table_name: lending_rate

  webgui_port: 5010
  webgui_debug: yes

als_test:
  <<: *app
  test: test
