%YAML 1.2
---
# Config for the application
# --------------------------
als: &app
  test: test
  root_dir: /home/stas/dev/eclipse_workspace/AutomaticLendingSystem # change this

als_test:
  <<: *app
  test: test
